version: '3'

vars:
  PROTO_ROOT: proto
  OUT_DIR: gen/go

tasks:
  gen:
    desc: 生成 Go + gRPC 代码到 gen/go/proto 目录
    cmds:
      - mkdir -p {{.OUT_DIR}}/proto/datasource/v1
      - protoc --proto_path={{.PROTO_ROOT}} \
               --go_out={{.OUT_DIR}} --go_opt=paths=source_relative \
               --go-grpc_out={{.OUT_DIR}} --go-grpc_opt=paths=source_relative \
               {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  clean:
    desc: 清理生成目录
    cmds:
      - rm -rf {{.OUT_DIR}}
