version: '3'

vars:
  PROTO_ROOT: proto
  OUT_DIR: gen/go/proto

tasks:
  gen:
    desc: 生成 Go + gRPC 代码到 {{.OUT_DIR}}/proto 目录
    deps: [mkdir] # 依赖可以保留，确保根目录存在
    cmds:
      - cmd: |
          protoc --proto_path={{.PROTO_ROOT}} \
                 --go_out={{.OUT_DIR}} --go_opt=paths=source_relative \
                 --go-grpc_out={{.OUT_DIR}} --go-grpc_opt=paths=source_relative \
                 {{.PROTO_ROOT}}/datasource/v1/datasource.proto

  mkdir:
    desc: 确保根输出目录存在
    cmds:
      - cmd: mkdir -p {{.OUT_DIR}}
        platforms: [linux, darwin]

      - cmd: >
          powershell -NoProfile -Command
          "if (-not (Test-Path '{{.OUT_DIR}}')) {
             New-Item -ItemType Directory -Path '{{.OUT_DIR}}' -Force | Out-Null
           }"
        platforms: [windows]

  clean:
    desc: 清理生成目录
    cmds:
      - cmd: rm -rf {{.OUT_DIR}}
        platforms: [linux, darwin]
      - cmd: >
          powershell -NoProfile -Command
          "if (Test-Path '{{.OUT_DIR}}') {
             Remove-Item -Recurse -Force '{{.OUT_DIR}}' | Out-Null
           }"
        platforms: [windows]