# configs/config.yaml
server:
  port: 10224
  log_level: "info"

plugin_management:
  # install_directory 现在直接指向我们期望的插件安装位置
  install_directory: "./instance/plugins"
  repositories:
    - name: "本地测试仓库"
      url: "./configs/local_repository.json" # 相对于项目根目录即可
      enabled: true