name: Build & Check Proto

on:
  push:
    paths:
      - 'proto/**'
      - 'Taskfile.yml'
  pull_request:
    paths:
      - 'proto/**'
      - 'Taskfile.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Task (cross-platform task runner)
        uses: arduino/setup-task@v2

      - name: Install Protobuf + Plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Generate Protobuf Files
        run: task gen

      - name: Check for Uncommitted Generated Files
        run: |
          git diff --exit-code || (echo "::error::Protobuf 编译文件未提交！请运行 'task gen' 并提交。" && exit 1)
